from typing import Annotated, Sequence
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from langchain_openai import ChatOpenAI
from tradingagents.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState


# 研究员队伍辩论状态（多空研究员对抚辩论的局部状态）
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # 多方（看多）研究员历史发言记录
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # 空方（看空）研究员历史发言记录
    history: Annotated[str, "Conversation history"]          # 全部辩论历史合辑
    current_response: Annotated[str, "Latest response"]      # 最新一次发言内容
    judge_decision: Annotated[str, "Final judge decision"]   # Research Manager 裁判结果
    count: Annotated[int, "Length of the current conversation"]  # 当前辩论轮次计数


# 风险管理队伍辩论状态（激进/保守/中性三方辩论的局部状态）
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # 激进方历史发言记录
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # 保守方历史发言记录
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # 中性方历史发言记录
    history: Annotated[str, "Conversation history"]          # 全部讨论历史合辑
    latest_speaker: Annotated[str, "Analyst that spoke last"]  # 最近一次发言的分析师名称
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # 激进方最新辩论
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # 保守方最新辩论
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # 中性方最新辩论
    judge_decision: Annotated[str, "Judge's decision"]       # Risk Judge 最终裁判结果
    count: Annotated[int, "Length of the current conversation"]  # 当前讨论轮次计数


class AgentState(MessagesState):
    """整个图的全局状态，贯穿所有节点。"""
    company_of_interest: Annotated[str, "Company that we are interested in trading"]  # 分析目标公司代码
    trade_date: Annotated[str, "What date we are trading at"]  # 交易日期

    sender: Annotated[str, "Agent that sent this message"]  # 发送消息的 Agent 名称

    # ── 分析师层输出的四份报告 ─────────────────────────────────────────
    market_report: Annotated[str, "Report from the Market Analyst"]            # 市场技术指标报告
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]   # 社交媒体情绪报告
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]  # 全球宏观新闻报告
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]  # 基本面分析报告

    # ── 研究员辩论层结果 ─────────────────────────────────────────────
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]  # 多空辩论局部状态
    investment_plan: Annotated[str, "Plan generated by the Analyst"]  # Research Manager 制定的投资方案

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]  # 交易员制定的具体交易方案

    # ── 风险切山层结果 ─────────────────────────────────────────────
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]  # 风险辩论局部状态
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]  # 风险切山师输出的最终交易决策
